import { FormEvent, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Cpu, KeyRound, Pencil, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { studioApi } from "../api";
import { Badge, Button, Card, Empty, LoadFailure, PageTitle, SectionTitle, Skeleton } from "../components/ui";
import { studioKeys, useArticleModels } from "../queries";

export function StudioSettingsPage() {
  const profiles = useArticleModels();
  const client = useQueryClient();
  const [name, setName] = useState(""); const [provider, setProvider] = useState("openai");
  const [model, setModel] = useState(""); const [apiBase, setApiBase] = useState(""); const [credential, setCredential] = useState("");
  const [isDefault, setDefault] = useState(true); const [runtime, setRuntime] = useState<Record<string, unknown> | null>(null);
  const [editingId, setEditingId] = useState(""); const [expectedRevision, setExpectedRevision] = useState(0);
  const save = useMutation({ mutationFn: () => studioApi.saveArticleModel({ name, provider, model, api_base: apiBase, credential, is_default: isDefault, active: true, parameters: {}, ...(editingId ? { expected_revision: expectedRevision } : {}) }, editingId), onSuccess: async () => { toast.success("文章模型已保存，凭据只进入操作系统凭据存储"); setName(""); setModel(""); setCredential(""); setEditingId(""); setExpectedRevision(0); await client.invalidateQueries({ queryKey: studioKeys.models }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "保存失败") });
  const test = useMutation({ mutationFn: studioApi.testArticleModel, onSuccess: () => toast.success("文章模型连接成功"), onError: (error) => toast.error(error instanceof Error ? error.message : "连接失败") });
  const remove = useMutation({ mutationFn: studioApi.deleteArticleModel, onSuccess: () => client.invalidateQueries({ queryKey: studioKeys.models }) });
  const probe = useMutation({ mutationFn: studioApi.testRuntime, onSuccess: (value) => { setRuntime(value); toast.success(value.available ? "Codex App Server 能力完整" : "Codex 尚未就绪"); }, onError: (error) => toast.error(error instanceof Error ? error.message : "探测失败") });
  return <div className="page settings-page">
    <PageTitle eyebrow="System Settings" title="设置" detail="工程执行只使用本地 Codex App Server；文章模型与产品分析模型独立。" />
    <div className="settings-studio-grid">
      <Card><SectionTitle title="Codex 工程内核" meta="唯一执行后端" /><div className="runtime-contract"><Cpu /><div><b>Local Codex App Server</b><p>执行前强制验证 Plan、Goal、Detached Review、Skill、结构化输出、流式事件和交互能力。</p></div></div><Button onClick={() => probe.mutate()} disabled={probe.isPending}>{probe.isPending ? "正在探测…" : "验证 Codex 能力"}</Button>{runtime && <div className="capability-grid">{Object.entries((runtime.capabilities || {}) as Record<string, boolean>).map(([key, ready]) => <span key={key} className={ready ? "ready" : "missing"}>{ready ? <CheckCircle2 /> : <Cpu />}{key}</span>)}</div>}</Card>
      <Card><SectionTitle title="文章模型 Profiles" meta="无代码与仓库工具" />{profiles.isLoading ? <Skeleton className="h-64" /> : profiles.isError ? <LoadFailure onRetry={() => profiles.refetch()} /> : profiles.data?.profiles.length ? <div className="model-profiles">{profiles.data.profiles.map((profile) => <article key={profile.id}><header><div><h3>{profile.name}</h3><p>{profile.provider} · {profile.model}</p></div>{profile.is_default && <Badge value="default">默认</Badge>}</header><footer><span><KeyRound size={13} />{profile.credential_configured ? profile.credential_mask : "未配置凭据"}</span><Button size="sm" onClick={() => test.mutate(profile.id)}>测试</Button><Button size="icon" variant="ghost" onClick={() => { setEditingId(profile.id); setExpectedRevision(profile.revision); setName(profile.name); setProvider(profile.provider); setModel(profile.model); setApiBase(profile.api_base); setCredential(""); setDefault(profile.is_default); }} aria-label="修改"><Pencil size={14} /></Button><Button size="icon" variant="ghost" onClick={() => remove.mutate(profile.id)} aria-label="停用"><Trash2 size={14} /></Button></footer></article>)}</div> : <Empty title="还没有文章模型" detail="支持 LiteLLM 已知 provider 和 OpenAI-compatible endpoint。" />}</Card>
    </div>
    <Card><SectionTitle title={editingId ? "修改文章模型" : "新增文章模型"} meta={<span className="secure-copy"><ShieldCheck />读取接口和日志永不返回明文凭据</span>} /><form className="model-form" onSubmit={(event: FormEvent) => { event.preventDefault(); save.mutate(); }}><div className="field-grid"><label className="field"><span>名称</span><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="写作模型" /></label><label className="field"><span>Provider</span><input required value={provider} onChange={(event) => setProvider(event.target.value)} placeholder="openai / anthropic / openai-compatible" /></label><label className="field"><span>Model</span><input required value={model} onChange={(event) => setModel(event.target.value)} placeholder="gpt-5-mini" /></label><label className="field"><span>Base URL（可选）</span><input value={apiBase} onChange={(event) => setApiBase(event.target.value)} placeholder="https://…/v1" /></label><label className="field"><span>API Key</span><input type="password" value={credential} onChange={(event) => setCredential(event.target.value)} autoComplete="new-password" placeholder={editingId ? "留空则保留现有凭据" : "保存后不可读取"} /></label><label className="checkbox-field"><input type="checkbox" checked={isDefault} onChange={(event) => setDefault(event.target.checked)} /><span>设为默认 Article Model</span></label></div><div className="wizard-actions">{editingId && <Button type="button" onClick={() => { setEditingId(""); setExpectedRevision(0); setName(""); setModel(""); setCredential(""); }}>取消修改</Button>}<Button variant="primary" type="submit" disabled={save.isPending}><Plus size={15} />保存 Profile</Button></div></form></Card>
  </div>;
}
